apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jenkins
  namespace: jenkins-test
spec:
  url: https://charts.jenkins.io
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jenkins
  namespace: jenkins-test
spec:
  interval: 5m
  chart:
    spec:
      chart: jenkins
      version: '3.5.7'
      sourceRef:
        kind: HelmRepository
        name: jenkins
        namespace: jenkins-test
  values:
    controller:
      adminUser: admin
      adminPassword: admin
    persistence:
      enabled: true
      size: 8Gi
    service:
      type: ClusterIP
      port: 8080
    ingress:
      enabled: true
      className: "nginx"
      hosts:
        - host: jenkins.rdevapp.org
          paths:
            - path: /
              pathType: Prefix