apiVersion: v1
kind: Namespace
metadata:
  name: podinfo-test
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: podinfo
  namespace: podinfo-test
spec:
  url: https://stefanprodan.github.io/podinfo
  interval: 10m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo-test
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: '6.0.0'
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: podinfo-test
  values:
    replicaCount: 1
    ingress:
      enabled: true
      className: "nginx"
      hosts:
        - host: podinfo.rdevapp.org
          paths:
            - path: /
              pathType: Prefix